### ISSUE TITLE
Bot not registering entries 

### ISSUE THREAD

**Issue by Merovin90** [alexberryman/DiscordWordle#10]
It seems if someone posts their Wordle score incorrectly, resulting in the bot not registering the results, if they then repost it correctly, the bot doesn’t pick them up. Attached the most recent example of this:

![F9161331-18CF-4C0F-AAEE-7639F5893953](https://user-images.githubusercontent.com/14044197/150126979-2ece7e82-808f-48cd-a830-ee22be093f69.jpeg)

**Comment by Zonkil9** [comment]
Discordle is not responding at all right now.

**Comment by Merovin90** [comment]
@Zonkil9 yeah bot appears to be offline at the moment, but at the time of the above example I posted, the bot was online

**Comment by alexberryman** [comment]
The bot has been crashing a bit as it has become more popular. There are some servers inputting `quips` in a way that is causing it to panic and crash.

I'll work on the logging/error handling around this to reduce the crashes. In the meantime I'm keeping an eye on it and trying to restart it whenever it happens.

**Comment by alexberryman** [comment]
I think I solved the main bug that caused the bot to crash. I'll monitor it for a few days then close this issue if no new crashes happen.
