### ISSUE TITLE
Add commands for enabling/disabling quips to the help message

### ISSUE THREAD

**Issue by gabbard** [alexberryman/DiscordWordle#24]
The users on my server wished to disable the quips.  I was able to find the command through [this Github issue](https://github.com/alexberryman/DiscordWordle/issues/9), but less technical users might not find this, so it would be good to add the `quip enable` and `quip disable` to the help message.

**Comment by alexberryman** [comment]
In a release 18 days ago, along with the whole feature, the `quip disable/enable` was added  to the `@mention help` command as lines 4 and 5:
https://github.com/alexberryman/DiscordWordle/blame/main/cmd/bot/help.go#L13-L14

![image](https://user-images.githubusercontent.com/1881846/152690913-b9af5ca1-d9ed-423f-ad67-b50e7fa71a21.png)

Are you not seeing this `help` text in your server?

**Comment by gabbard** [comment]
Oh, oops - I forgot that when I set up Heroku to run my own instance of the server, I had deployed from a fork I made of your repo rather than your repo directly. 🤦  Actually merging in the updated code works. :-). Apologies for the false alarm, and thanks for the bot!

**Comment by alexberryman** [comment]
Cool. Glad to hear you are enjoying it!
